---
pidfile_directory: .robot_sweatshop/run
logfile_directory: .robot_sweatshop/log
job_directory: .robot_sweatshop/jobs
workspace_directory: .robot_sweatshop/workspaces
http_port: 8080
http_bind: 0.0.0.0
