---
pidfile_path: .robot_sweatshop/run
logfile_path: .robot_sweatshop/log
job_path: .robot_sweatshop/jobs
workspace_path: .robot_sweatshop/workspaces
database_path: .robot_sweatshop/db
scripts_path: .robot_sweatshop/scripts
http_bind: 0.0.0.0
http_cross_origin: true
overseer_port: 10554
api_port: 10555
conveyor_port: 10556
payload_parser_port: 10557
job_dictionary_port: 10558
worker_port: 10559
logger_port: 10560
reflector_port: 10561
api_url: http://localhost:10555
job_timeout_length: 300 # 5 minutes
worker_count: 2
