---
pidfile_directory: /var/run/robot_sweatshop
logfile_directory: /var/log/robot_sweatshop
job_directory: /etc/robot_sweatshop/jobs
workspace_directory: /etc/robot_sweatshop/workspaces
moneta_directory: /var/db/robot_sweatshop
user: ci-bot
group: nogroup
http_port: 8080
http_bind: 0.0.0.0
